name: 'Changelog Reminder'
description: 'If there is not a changelog in the PR add a comment to remind the committer'
author: 'GitHub'
icon: 'check'
color: 'green'
runs:
  using: 'node12'
  main: 'lib/main.js'
